export const dataProducts = [
  {
    id: 1,
    city: 'Los Angeles',
    type: 'House',
    title: 'Modern home in city center',
    price: 1400,
    features: '3 Beds - 2 Baths',
    plus: true,
    amenities: 'Balcony Pool Pet Friendly',
    stars: 5,
    url: 'https://s6.uupload.ir/files/la-1_fb.jpg',
  },
  {
    id: 2,
    city: 'Los Angeles',
    type: 'House',
    title: 'Modern home in city center 2',
    price: 1200,
    features: '1 Beds - 4 Baths',
    plus: true,
    amenities: 'Balcony Pool Pet Friendly',
    stars: 2,
    url: 'https://s6.uupload.ir/files/la-2_qbqt.jpg',
  },
  {
    id: 3,
    city: 'Los Angeles',
    type: 'Apartment',
    title: 'Modern home in city center 3',
    price: 5400,
    features: '3 Beds - 3 Baths',
    plus: false,
    amenities: 'Balcony Pool Pet Friendly',
    stars: 4,
    url: 'https://s6.uupload.ir/files/la-3_fa53.jpg',
  },
  {
    id: 4,
    city: 'Phoenix',
    type: 'Loft',
    title: 'Modern home in city center',
    price: 2500,
    features: '2 Beds - 3 Baths',
    plus: false,
    amenities: 'Balcony Pool Pet Friendly',
    stars: 3,
    url: 'https://s6.uupload.ir/files/ph-1_6vv5.jpg',
  },
  {
    id: 5,
    city: 'Phoenix',
    type: 'Townhouse',
    title: 'Modern home in city center',
    price: 6090,
    features: '4 Beds - 2 Baths',
    plus: true,
    amenities: 'Balcony Pool Pet Friendly',
    stars: 3,
    url: 'https://s6.uupload.ir/files/ph-2_m9dm.jpg',
  },
  {
    id: 6,
    city: 'Phoenix',
    type: 'House',
    title: 'Modern home in city center',
    price: 5000,
    features: '4 Beds - 1 Baths',
    plus: false,
    amenities: 'Balcony Pool Pet Friendly',
    stars: 4,
    url: 'https://s6.uupload.ir/files/ph-3_6gcj.jpg',
  },
]
